<?php

const SEED_USERS = [
    // 3 admins
    ['name' => 'Admin', 'email' => 'admin@afrochick.com', 'password' => 'admin1234', 'role' => 'admin'],
    ['name' => 'Sarah Okonkwo', 'email' => 'admin2@afrochick.com', 'password' => 'admin1234', 'role' => 'admin'],
    ['name' => 'James Lindberg', 'email' => 'admin3@afrochick.com', 'password' => 'admin1234', 'role' => 'admin'],
    // 10 users
    ['name' => 'Demo User', 'email' => 'demo@afrochick.com', 'password' => 'demo1234', 'role' => 'user'],
    ['name' => 'Amara Kofi', 'email' => 'user2@afrochick.com', 'password' => 'demo1234', 'role' => 'user'],
    ['name' => 'Joel Richards', 'email' => 'user3@afrochick.com', 'password' => 'demo1234', 'role' => 'user'],
    ['name' => 'Sofia Laurent', 'email' => 'user4@afrochick.com', 'password' => 'demo1234', 'role' => 'user'],
    ['name' => 'Chioma Adeyemi', 'email' => 'user5@afrochick.com', 'password' => 'demo1234', 'role' => 'user'],
    ['name' => 'Marcus Chen', 'email' => 'user6@afrochick.com', 'password' => 'demo1234', 'role' => 'user'],
    ['name' => 'Fatima Hassan', 'email' => 'user7@afrochick.com', 'password' => 'demo1234', 'role' => 'user'],
    ['name' => 'Elena Vasquez', 'email' => 'user8@afrochick.com', 'password' => 'demo1234', 'role' => 'user'],
    ['name' => 'David Osei', 'email' => 'user9@afrochick.com', 'password' => 'demo1234', 'role' => 'user'],
    ['name' => 'Priya Sharma', 'email' => 'user10@afrochick.com', 'password' => 'demo1234', 'role' => 'user'],
];

const SEED_PRODUCTS = [
    [
        'name' => 'Sage Glow Niacinamide Serum',
        'category' => 'Serums',
        'status' => 'approved',
        'image' => '🧴',
        'price' => '$42',
        'ingredients' => ['Niacinamide 10%', 'Zinc PCA', 'Hyaluronic Acid'],
        'benefits' => ['Controls oil', 'Minimizes pores', 'Brightens tone'],
        'description' => 'A lightweight serum formulated for oily and combination skin types.',
    ],
    [
        'name' => 'Ceramide Barrier Cream',
        'category' => 'Moisturizers',
        'status' => 'approved',
        'image' => '💧',
        'price' => '$38',
        'ingredients' => ['Ceramides', 'Squalane', 'Panthenol'],
        'benefits' => ['Restores barrier', 'Deep hydration', 'Soothes dryness'],
        'description' => 'Rich yet breathable moisturizer for dry and sensitive skin.',
    ],
    [
        'name' => 'Vitamin C Radiance Drops',
        'category' => 'Serums',
        'status' => 'approved',
        'image' => '✨',
        'price' => '$48',
        'ingredients' => ['L-Ascorbic Acid 15%', 'Vitamin E', 'Ferulic Acid'],
        'benefits' => ['Fades dark spots', 'Evens tone', 'Antioxidant shield'],
        'description' => 'Clinical-strength brightening serum for hyperpigmentation concerns.',
    ],
    [
        'name' => 'Mineral Shield SPF 50',
        'category' => 'Sunscreens',
        'status' => 'approved',
        'image' => '☀️',
        'price' => '$34',
        'ingredients' => ['Zinc Oxide', 'Titanium Dioxide', 'Squalane'],
        'benefits' => ['Broad spectrum', 'No white cast', 'Reef safe'],
        'description' => 'Silky mineral sunscreen for daily sensitive-skin protection.',
    ],
    [
        'name' => 'Rosemary Root Strengthening Oil',
        'category' => 'Hair Oils',
        'status' => 'approved',
        'image' => '🌿',
        'price' => '$29',
        'ingredients' => ['Rosemary Extract', 'Biotin', 'Castor Oil'],
        'benefits' => ['Reduces hair fall', 'Stimulates roots', 'Adds shine'],
        'description' => 'Scalp treatment oil targeting thinning and weak roots.',
    ],
    [
        'name' => 'Calm Scalp Shampoo',
        'category' => 'Shampoo',
        'status' => 'approved',
        'image' => '🍃',
        'price' => '$24',
        'ingredients' => ['Zinc PCA', 'Tea Tree Oil', 'Oat Extract'],
        'benefits' => ['Fights dandruff', 'Soothes itch', 'Gentle cleanse'],
        'description' => 'Dermatologist-inspired shampoo for flaky and sensitive scalps.',
    ],
    [
        'name' => 'Keratin Silk Conditioner',
        'category' => 'Conditioner',
        'status' => 'approved',
        'image' => '💆',
        'price' => '$22',
        'ingredients' => ['Hydrolyzed Keratin', 'Argan Oil', 'Glycerin'],
        'benefits' => ['Tames frizz', 'Repairs breakage', 'Smooth finish'],
        'description' => 'Nourishing conditioner for frizzy, damaged, and curly hair.',
    ],
    [
        'name' => 'Overnight Repair Hair Mask',
        'category' => 'Hair Masks',
        'status' => 'approved',
        'image' => '🌸',
        'price' => '$36',
        'ingredients' => ['Peptides', 'Shea Butter', 'Panthenol'],
        'benefits' => ['Deep repair', 'Restores elasticity', 'Softens ends'],
        'description' => 'Intensive mask for split ends and chemically treated hair.',
    ],
    [
        'name' => 'Centella Calm Gel',
        'category' => 'Moisturizers',
        'status' => 'approved',
        'image' => '🧪',
        'price' => '$32',
        'ingredients' => ['Centella Asiatica', 'Allantoin', 'Madecassoside'],
        'benefits' => ['Reduces redness', 'Calms irritation', 'Lightweight hydration'],
        'description' => 'Cooling gel moisturizer ideal for reactive and sensitive skin.',
    ],
    [
        'name' => 'Scalp Detox Treatment',
        'category' => 'Scalp Treatments',
        'status' => 'approved',
        'image' => '🔬',
        'price' => '$40',
        'ingredients' => ['Salicylic Acid', 'Piroctone Olamine', 'Niacinamide'],
        'benefits' => ['Clears buildup', 'Balances scalp', 'Refreshes roots'],
        'description' => 'Weekly scalp treatment for oily roots and product residue.',
    ],
];

const SEED_ANALYSES = [
    ['userEmail' => 'demo@afrochick.com', 'type' => 'skin', 'profile_label' => 'Combination'],
    ['userEmail' => 'demo@afrochick.com', 'type' => 'hair', 'profile_label' => 'Curly'],
    ['userEmail' => 'user2@afrochick.com', 'type' => 'skin', 'profile_label' => 'Oily'],
    ['userEmail' => 'user3@afrochick.com', 'type' => 'hair', 'profile_label' => 'Wavy'],
    ['userEmail' => 'user5@afrochick.com', 'type' => 'skin', 'profile_label' => 'Sensitive'],
    ['userEmail' => 'user8@afrochick.com', 'type' => 'hair', 'profile_label' => 'Coily'],
];
